启动3000端口
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
数据库连接失败 { MongoNetworkError: failed to connect to server [127.0.0.1:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/Users/fuhaoliang/Desktop/公司/cms-typescript/node_modules/mongodb/lib/core/topologies/server.js:431:11)
    at emitOne (events.js:116:13)
    at Pool.emit (events.js:211:7)
    at createConnection (/Users/fuhaoliang/Desktop/公司/cms-typescript/node_modules/mongodb/lib/core/connection/pool.js:559:14)
    at connect (/Users/fuhaoliang/Desktop/公司/cms-typescript/node_modules/mongodb/lib/core/connection/pool.js:973:11)
    at makeConnection (/Users/fuhaoliang/Desktop/公司/cms-typescript/node_modules/mongodb/lib/core/connection/connect.js:39:11)
    at callback (/Users/fuhaoliang/Desktop/公司/cms-typescript/node_modules/mongodb/lib/core/connection/connect.js:261:5)
    at Socket.err (/Users/fuhaoliang/Desktop/公司/cms-typescript/node_modules/mongodb/lib/core/connection/connect.js:286:7)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at args.(anonymous function) (/usr/local/lib/node_modules/pm2/node_modules/event-loop-inspector/index.js:133:29)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
  name: 'MongoNetworkError',
  errorLabels: [ 'TransientTransactionError' ],
  [Symbol(mongoErrorContextSymbol)]: {} }
启动3000端口
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
数据库连接失败 { MongoNetworkError: failed to connect to server [127.0.0.1:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/Users/fuhaoliang/Desktop/公司/cms-typescript/node_modules/mongodb/lib/core/topologies/server.js:431:11)
    at emitOne (events.js:116:13)
    at Pool.emit (events.js:211:7)
    at createConnection (/Users/fuhaoliang/Desktop/公司/cms-typescript/node_modules/mongodb/lib/core/connection/pool.js:559:14)
    at connect (/Users/fuhaoliang/Desktop/公司/cms-typescript/node_modules/mongodb/lib/core/connection/pool.js:973:11)
    at makeConnection (/Users/fuhaoliang/Desktop/公司/cms-typescript/node_modules/mongodb/lib/core/connection/connect.js:39:11)
    at callback (/Users/fuhaoliang/Desktop/公司/cms-typescript/node_modules/mongodb/lib/core/connection/connect.js:261:5)
    at Socket.err (/Users/fuhaoliang/Desktop/公司/cms-typescript/node_modules/mongodb/lib/core/connection/connect.js:286:7)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at args.(anonymous function) (/usr/local/lib/node_modules/pm2/node_modules/event-loop-inspector/index.js:133:29)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
  name: 'MongoNetworkError',
  errorLabels: [ 'TransientTransactionError' ],
  [Symbol(mongoErrorContextSymbol)]: {} }
启动3000端口
数据库连接失败 { MongoParseError: Invalid connection string
    at parseConnectionString (/Users/fuhl/fuhaoliang/cms-typescript/node_modules/mongodb/lib/core/uri_parser.js:507:21)
    at connect (/Users/fuhl/fuhaoliang/cms-typescript/node_modules/mongodb/lib/operations/connect.js:268:3)
    at ConnectOperation.execute (/Users/fuhl/fuhaoliang/cms-typescript/node_modules/mongodb/lib/operations/connect.js:191:5)
    at executeOperation (/Users/fuhl/fuhaoliang/cms-typescript/node_modules/mongodb/lib/operations/execute_operation.js:83:26)
    at MongoClient.connect (/Users/fuhl/fuhaoliang/cms-typescript/node_modules/mongodb/lib/mongo_client.js:216:10)
    at Promise (/Users/fuhl/fuhaoliang/cms-typescript/node_modules/mongoose/lib/connection.js:632:12)
    at new Promise (<anonymous>)
    at NativeConnection.Connection.openUri (/Users/fuhl/fuhaoliang/cms-typescript/node_modules/mongoose/lib/connection.js:629:19)
    at Mongoose.connect (/Users/fuhl/fuhaoliang/cms-typescript/node_modules/mongoose/lib/index.js:328:15)
    at Object.<anonymous> (/Users/fuhl/fuhaoliang/cms-typescript/src/config/db.ts:5:10)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
  name: 'MongoParseError',
  [Symbol(mongoErrorContextSymbol)]: {} }
